export default [
  {
    path: '/dashboard',
    name: 'overview',
    icon: 'dashboard',
    component: './Dashboard',
  },
  {
    path: '/workspace',
    name: 'workspace',
    icon: 'appstore',
    routes: [
      { path: '/workspace', redirect: '/workspace/markets' },
      { path: '/workspace/disputes',   name: 'disputes',   component: './Disputes/List' },
      { path: '/workspace/markets',    name: 'markets',    component: './MyQueue' },
      { path: '/workspace/events',     name: 'events',     component: './MyQueueEvents' },

      { path: '/workspace/admin-events', name: 'special-events', component: './AdminEvents/List' },
      { path: '/workspace/campaigns',      name: 'campaigns',      component: './Campaigns' },
      {
        path: '/workspace/event-creation',
        name: 'event-creation',
        routes: [
          { path: '/workspace/event-creation',          redirect: '/workspace/event-creation/new' },
          { path: '/workspace/event-creation/new',      name: 'create',        component: './Events/Create' },
          { path: '/workspace/event-creation/campaign', name: 'campaign',      component: './Campaigns/Create' },
          { path: '/workspace/event-creation/special',  name: 'special-event', component: './AdminEvents/Create' },
        ],
      },
      { path: '/workspace/import',     name: 'import',     component: './Import/Polymarket' },
      { path: '/workspace/claims',     name: 'claims',     component: './Claims' },

      { path: '/workspace/disputes/:id', component: './Disputes/Detail' },
    ],
  },
  {
    path: '/data',
    name: 'data',
    icon: 'database',
    routes: [
      { path: '/data', redirect: '/data/markets' },
      { path: '/data/markets', name: 'markets', component: './Markets' },
      { path: '/data/events',  name: 'events',  component: './Events/List' },
      { path: '/data/bets',    name: 'bets',    component: './Bets' },
      { path: '/data/invitations', name: 'invitations', component: './Invitations' },
      { path: '/data/leaderboard', name: 'leaderboard', component: './Leaderboard' },
      { path: '/data/tags',    name: 'tags',     component: './Tags' },
      { path: '/data/events/:slug', component: './Events/Detail' },
      { path: '/data/events/:slug/markets/:idx', component: './Events/MarketDetail' },
    ],
  },
  {
    path: '/ops',
    name: 'ops',
    icon: 'rocket',
    routes: [
      { path: '/ops', redirect: '/ops/users' },
      { path: '/ops/users',      name: 'users',      icon: 'user',     component: './Users' },
      { path: '/ops/activities', name: 'activities', icon: 'appstore', component: './Activities' },
      {
        path: '/ops/push',
        name: 'push',
        icon: 'notification',
        routes: [
          { path: '/ops/push', redirect: '/ops/push/compose' },
          { path: '/ops/push/compose', name: 'compose', icon: 'edit',    component: './Push/Compose' },
          { path: '/ops/push/history', name: 'history', icon: 'history', component: './Push/History' },
        ],
      },
      {
        path: '/ops/invite',
        name: 'invite',
        icon: 'gift',
        routes: [
          { path: '/ops/invite', redirect: '/ops/invite/payout' },
          { path: '/ops/invite/payout', name: 'payout', component: './InvitePayout' },
        ],
      },
      // Reward Payouts / Treasury are not wired for Solana in the MVP.
      // {
      //   path: '/ops/rewards',
      //   name: 'rewards',
      //   icon: 'trophy',
      //   component: './Rewards',
      // },
      // { path: '/ops/rewards/:id', component: './Rewards/Detail' },

    ],
  },
  {
    path: '/settings',
    name: 'settings',
    icon: 'setting',
    routes: [
      { path: '/settings', redirect: '/settings/admin-accounts' },
      { path: '/settings/admin-accounts', name: 'admin-accounts', icon: 'safetyCertificate', component: './AdminAccounts' },
      { path: '/settings/operators',      name: 'admin-wallets',  icon: 'team',              component: './Operators' },
      { path: '/settings/config',         name: 'global-config',  icon: 'tool',              component: './Config' },
      { path: '/settings/invite',         name: 'invite-config',  icon: 'gift',              component: './InviteConfig' },
      // Treasury is not wired for Solana in the MVP.
      // { path: '/settings/treasury',       name: 'treasury',       icon: 'wallet',            component: './Treasury' },
    ],
  },
  // Legacy redirects.
  { path: '/', redirect: '/dashboard' },
  { path: '/my-queue', redirect: '/workspace/markets' },
  { path: '/tasks', redirect: '/workspace/markets' },
  { path: '/tasks/queue', redirect: '/workspace/markets' },
  { path: '/tasks/events', redirect: '/workspace/events' },
  { path: '/tasks/disputes', redirect: '/workspace/disputes' },
  { path: '/disputes', redirect: '/workspace/disputes' },
  { path: '/disputes/list', redirect: '/workspace/disputes' },
  { path: '/disputes/:id', component: './Disputes/Detail' },
  { path: '/markets', redirect: '/data/markets' },
  { path: '/events', redirect: '/data/events' },
  { path: '/events/list', redirect: '/data/events' },
  { path: '/workspace/create', redirect: '/workspace/event-creation/new' },
  { path: '/workspace/admin-events/create', redirect: '/workspace/event-creation/special' },
  { path: '/events/create', redirect: '/workspace/event-creation/new' },
  { path: '/events/tags', redirect: '/data/tags' },
  { path: '/events/:slug', component: './Events/Detail' },
  { path: '/events/:slug/markets/:idx', component: './Events/MarketDetail' },
  { path: '/import', redirect: '/workspace/import' },
  { path: '/import/polymarket', redirect: '/workspace/import' },
  { path: '/tags', redirect: '/data/tags' },
  { path: '/users', redirect: '/ops/users' },
  { path: '/activities', redirect: '/ops/activities' },
  { path: '/ops/campaigns', redirect: '/workspace/campaigns' },
  { path: '/ops/invite/config', redirect: '/settings/invite' },
  { component: './exception/404', path: '/*' },
];
