/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketsEventIdRouteImport } from './routes/markets.$eventId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsEventIdRoute = MarketsEventIdRouteImport.update({
  id: '/markets/$eventId',
  path: '/markets/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/predictions': typeof PredictionsRoute
  '/profile': typeof ProfileRoute
  '/markets/$eventId': typeof MarketsEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/predictions': typeof PredictionsRoute
  '/profile': typeof ProfileRoute
  '/markets/$eventId': typeof MarketsEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/predictions': typeof PredictionsRoute
  '/profile': typeof ProfileRoute
  '/markets/$eventId': typeof MarketsEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/leaderboard'
    | '/notifications'
    | '/predictions'
    | '/profile'
    | '/markets/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/leaderboard'
    | '/notifications'
    | '/predictions'
    | '/profile'
    | '/markets/$eventId'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/leaderboard'
    | '/notifications'
    | '/predictions'
    | '/profile'
    | '/markets/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  LeaderboardRoute: typeof LeaderboardRoute
  NotificationsRoute: typeof NotificationsRoute
  PredictionsRoute: typeof PredictionsRoute
  ProfileRoute: typeof ProfileRoute
  MarketsEventIdRoute: typeof MarketsEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/$eventId': {
      id: '/markets/$eventId'
      path: '/markets/$eventId'
      fullPath: '/markets/$eventId'
      preLoaderRoute: typeof MarketsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  LeaderboardRoute: LeaderboardRoute,
  NotificationsRoute: NotificationsRoute,
  PredictionsRoute: PredictionsRoute,
  ProfileRoute: ProfileRoute,
  MarketsEventIdRoute: MarketsEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
