"""Solana on-chain transaction and event parsing utilities.

This module provides a Python-only way to inspect Solana transactions that
interact with the PolyMind parimutuel program. It is shared by:

- ``app.workers.indexer`` for ingesting on-chain events into PostgreSQL
- API write endpoints (``propose/finalize/void/dispute/claim``) for verifying
  that a submitted signature actually executes the expected instruction.

The concrete instruction discriminators and event layouts below are placeholders
until the Anchor IDL / program source is finalized. The event *payload* schemas
are taken from the OLD Move contract (``smart-contract/parimutuel/sources``) so
that the indexer and API verification can be built before the Solana program is
ready.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Any

from solders.pubkey import Pubkey

from app.clients.solana import SolanaClient
from app.core.config import settings


class PolyMindInstruction(StrEnum):
    """Known PolyMind program instructions.

    The string values are human-readable names; the on-wire discriminators are
    the first 8 bytes of ``sha256("global:<name>")`` as generated by Anchor.
    """

    CREATE_EVENT = "create_event"
    ADD_MARKET = "add_market"
    BET = "bet"
    PROPOSE_OUTCOME = "propose_outcome"
    FINALIZE_PROPOSED = "finalize_proposed"
    ADMIN_FINALIZE = "admin_finalize"
    EMERGENCY_VOID = "emergency_void"
    EXPIRE_UNPROPOSED = "expire_unproposed"
    CLAIM = "claim"
    FILE_DISPUTE = "file_dispute"
    ADMIN_RESOLVE = "admin_resolve"


class PolyMindEventType(StrEnum):
    """Known PolyMind program events.

    Event logs on Solana have the form::

        Program data: <base64>

    where the decoded payload starts with an 8-byte event discriminator.

    The names intentionally mirror the OLD Move contract events in
    ``market.move`` and ``dispute.move`` so the indexer handlers map 1:1.
    """

    EVENT_CREATED = "EventCreated"
    MARKET_CREATED = "MarketCreated"
    BET = "Bet"
    OUTCOME_PROPOSED = "OutcomeProposed"
    DISPUTE_ACTIVE_SET = "DisputeActiveSet"
    FINALIZED = "Finalized"
    CLAIMED = "Claimed"
    CREATOR_SLASHED = "CreatorSlashed"
    CONFIG_UPDATED = "ConfigUpdated"
    SPONSOR_FLAGS_UPDATED = "SponsorFlagsUpdated"
    MIN_BET_UPDATED = "MinBetUpdated"
    PLATFORM_RAKE_WITHDRAWN = "PlatformRakeWithdrawn"
    CREATOR_REWARD_CLAIMED = "CreatorRewardClaimed"
    BOND_DEPOSITED = "BondDeposited"
    DISPUTE_RESOLVED = "DisputeResolved"
    BOND_REFUNDED = "BondRefunded"
    BOND_SLASHED = "BondSlashed"
    BOND_AMOUNT_UPDATED = "BondAmountUpdated"
    DISPUTE_SPONSOR_FLAGS_UPDATED = "DisputeSponsorFlagsUpdated"


# ---------------------------------------------------------------------------
# Placeholder discriminators
# ---------------------------------------------------------------------------
# TODO: replace with real values from the Anchor IDL once the program is
# finalized. The easiest way is to run ``anchor build`` and read the IDL, or
# compute sha256("global:<instruction_name>")[:8] for instructions and
# sha256("event:<EventName>")[:8] for events.
INSTRUCTION_DISCRIMINATORS: dict[PolyMindInstruction, bytes] = {
    PolyMindInstruction.CREATE_EVENT: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindInstruction.ADD_MARKET: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindInstruction.BET: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindInstruction.PROPOSE_OUTCOME: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindInstruction.FINALIZE_PROPOSED: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindInstruction.ADMIN_FINALIZE: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindInstruction.EMERGENCY_VOID: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindInstruction.EXPIRE_UNPROPOSED: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindInstruction.CLAIM: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindInstruction.FILE_DISPUTE: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindInstruction.ADMIN_RESOLVE: b"\x00\x00\x00\x00\x00\x00\x00\x00",
}

EVENT_DISCRIMINATORS: dict[PolyMindEventType, bytes] = {
    PolyMindEventType.EVENT_CREATED: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindEventType.MARKET_CREATED: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindEventType.BET: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindEventType.OUTCOME_PROPOSED: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindEventType.DISPUTE_ACTIVE_SET: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindEventType.FINALIZED: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindEventType.CLAIMED: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindEventType.CREATOR_SLASHED: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindEventType.CONFIG_UPDATED: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindEventType.SPONSOR_FLAGS_UPDATED: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindEventType.MIN_BET_UPDATED: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindEventType.PLATFORM_RAKE_WITHDRAWN: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindEventType.CREATOR_REWARD_CLAIMED: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindEventType.BOND_DEPOSITED: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindEventType.DISPUTE_RESOLVED: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindEventType.BOND_REFUNDED: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindEventType.BOND_SLASHED: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindEventType.BOND_AMOUNT_UPDATED: b"\x00\x00\x00\x00\x00\x00\x00\x00",
    PolyMindEventType.DISPUTE_SPONSOR_FLAGS_UPDATED: b"\x00\x00\x00\x00\x00\x00\x00\x00",
}

PROGRAM_ID: Pubkey = Pubkey.from_string(
    settings.solana_program_id or "11111111111111111111111111111111"
)

DISCRIMINATOR_LENGTH = 8


# ---------------------------------------------------------------------------
# Outcome / path constants (mirrors OLD Move contract)
# ---------------------------------------------------------------------------

SIDE_YES = 0
SIDE_NO = 1

OUTCOME_NONE = 0
OUTCOME_YES = 1
OUTCOME_NO = 2
OUTCOME_VOID = 3

# Finalization path codes from market.move.
FINALIZATION_PATH_FINALIZE_PROPOSED = 1
FINALIZATION_PATH_ADMIN_FINALIZE = 2
FINALIZATION_PATH_EMERGENCY_VOID = 3
FINALIZATION_PATH_CREATOR_EXPIRED = 4
FINALIZATION_PATH_CREATOR_SOLO_VOID = 5
FINALIZATION_PATH_SOLE_PARTICIPANT_VOID = 6
FINALIZATION_PATH_NO_OPPOSITION_VOID = 7


# ---------------------------------------------------------------------------
# Event payload dataclasses (schema from OLD Move contract)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class EventCreatedPayload:
    """Move event: market::EventCreated"""

    event_id: int
    creator: str
    question: str


@dataclass(frozen=True)
class MarketCreatedPayload:
    """Move event: market::MarketCreated"""

    event_id: int
    market_idx: int
    title: str
    deadline: int
    seed_side: int
    seed_amount: int
    external_source: int
    external_market_id: str
    external_aux_id: int


@dataclass(frozen=True)
class BetPayload:
    """Move event: market::Bet"""

    event_id: int
    market_idx: int
    user: str
    side: int  # 0 = YES, 1 = NO
    amount: int
    new_yes_pool: int
    new_no_pool: int


@dataclass(frozen=True)
class OutcomeProposedPayload:
    """Move event: market::OutcomeProposed"""

    event_id: int
    market_idx: int
    outcome: int  # 1 = YES, 2 = NO, 3 = VOID
    proposed_by: str
    proposed_at: int


@dataclass(frozen=True)
class DisputeActiveSetPayload:
    """Move event: market::DisputeActiveSet"""

    event_id: int
    market_idx: int
    active: bool


@dataclass(frozen=True)
class FinalizedPayload:
    """Move event: market::Finalized"""

    event_id: int
    market_idx: int
    outcome: int  # 1/2/3
    path: int  # see FINALIZATION_PATH_* constants
    finalized_at: int
    admin_reason: str
    creator_performed: bool
    platform_rake: int
    creator_reward: int
    distributable_pool: int


@dataclass(frozen=True)
class ClaimedPayload:
    """Move event: market::Claimed"""

    event_id: int
    market_idx: int
    user: str
    outcome: int
    payout: int


@dataclass(frozen=True)
class CreatorSlashedPayload:
    """Move event: market::CreatorSlashed"""

    event_id: int
    market_idx: int
    creator: str
    amount: int


@dataclass(frozen=True)
class ConfigUpdatedPayload:
    """Move event: market::ConfigUpdated"""

    creator_seed_min: int
    dispute_window_secs: int
    admin_timeout_secs: int
    platform_fee_bps: int
    platform_fee_max: int
    creator_reward_bps: int
    creator_reward_max: int
    creator_propose_timeout_secs: int
    expired_propose_mode: int  # 0 = takeover, 1 = slash
    single_side_only: bool


@dataclass(frozen=True)
class SponsorFlagsUpdatedPayload:
    """Move event: market::SponsorFlagsUpdated"""

    sponsor_create_event: bool
    sponsor_add_market: bool
    sponsor_bet: bool
    sponsor_propose: bool
    sponsor_finalize: bool
    sponsor_emergency_void: bool
    sponsor_expire_unproposed: bool


@dataclass(frozen=True)
class MinBetUpdatedPayload:
    """Move event: market::MinBetUpdated"""

    min_bet: int


@dataclass(frozen=True)
class PlatformRakeWithdrawnPayload:
    """Move event: market::PlatformRakeWithdrawn"""

    admin: str
    to: str
    amount: int


@dataclass(frozen=True)
class CreatorRewardClaimedPayload:
    """Move event: market::CreatorRewardClaimed"""

    creator: str
    amount: int


@dataclass(frozen=True)
class BondDepositedPayload:
    """Move event: dispute::BondDeposited"""

    event_id: int
    market_idx: int
    disputer: str
    amount: int
    claimed_outcome: int
    reason: str


@dataclass(frozen=True)
class DisputeResolvedPayload:
    """Move event: dispute::DisputeResolved"""

    event_id: int
    market_idx: int
    disputer: str
    resolved_outcome: int
    admin_reason: str
    refunded: bool
    amount: int


@dataclass(frozen=True)
class BondRefundedPayload:
    """Move event: dispute::BondRefunded"""

    event_id: int
    market_idx: int
    disputer: str
    amount: int


@dataclass(frozen=True)
class BondSlashedPayload:
    """Move event: dispute::BondSlashed"""

    event_id: int
    market_idx: int
    disputer: str
    amount: int


@dataclass(frozen=True)
class BondAmountUpdatedPayload:
    """Move event: dispute::BondAmountUpdated"""

    new_amount: int


@dataclass(frozen=True)
class DisputeSponsorFlagsUpdatedPayload:
    """Move event: dispute::SponsorFlagsUpdated"""

    sponsor_file_dispute: bool


# Convenience mapping from event type to payload dataclass.
EVENT_PAYLOAD_TYPES: dict[PolyMindEventType, type] = {
    PolyMindEventType.EVENT_CREATED: EventCreatedPayload,
    PolyMindEventType.MARKET_CREATED: MarketCreatedPayload,
    PolyMindEventType.BET: BetPayload,
    PolyMindEventType.OUTCOME_PROPOSED: OutcomeProposedPayload,
    PolyMindEventType.DISPUTE_ACTIVE_SET: DisputeActiveSetPayload,
    PolyMindEventType.FINALIZED: FinalizedPayload,
    PolyMindEventType.CLAIMED: ClaimedPayload,
    PolyMindEventType.CREATOR_SLASHED: CreatorSlashedPayload,
    PolyMindEventType.CONFIG_UPDATED: ConfigUpdatedPayload,
    PolyMindEventType.SPONSOR_FLAGS_UPDATED: SponsorFlagsUpdatedPayload,
    PolyMindEventType.MIN_BET_UPDATED: MinBetUpdatedPayload,
    PolyMindEventType.PLATFORM_RAKE_WITHDRAWN: PlatformRakeWithdrawnPayload,
    PolyMindEventType.CREATOR_REWARD_CLAIMED: CreatorRewardClaimedPayload,
    PolyMindEventType.BOND_DEPOSITED: BondDepositedPayload,
    PolyMindEventType.DISPUTE_RESOLVED: DisputeResolvedPayload,
    PolyMindEventType.BOND_REFUNDED: BondRefundedPayload,
    PolyMindEventType.BOND_SLASHED: BondSlashedPayload,
    PolyMindEventType.BOND_AMOUNT_UPDATED: BondAmountUpdatedPayload,
    PolyMindEventType.DISPUTE_SPONSOR_FLAGS_UPDATED: DisputeSponsorFlagsUpdatedPayload,
}


# ---------------------------------------------------------------------------
# Data classes for parsed transaction contents
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ParsedInstruction:
    """A PolyMind program instruction found inside a transaction."""

    instruction_name: PolyMindInstruction
    signer: str
    accounts: list[str]
    data: dict[str, Any]


@dataclass(frozen=True)
class PolyMindEvent:
    """A parsed PolyMind program event."""

    type: PolyMindEventType
    event_index: int
    payload: Any  # one of the *Payload dataclasses above


@dataclass(frozen=True)
class ParsedTransaction:
    """Result of parsing a full on-chain transaction."""

    signature: str
    slot: int
    block_time: int | None
    success: bool
    signer: str
    polymind_instructions: list[ParsedInstruction]
    polymind_events: list[PolyMindEvent]


class ChainParserError(Exception):
    """Raised when a transaction cannot be parsed or verified."""


# ---------------------------------------------------------------------------
# Low-level helpers
# ---------------------------------------------------------------------------


def _get_program_instructions(
    tx_json: dict[str, Any],
) -> list[tuple[int, dict[str, Any]]]:
    """Return (instruction_index, instruction) for all instructions targeting PROGRAM_ID.

    The returned ``instruction`` dict has keys:
        - ``programIdIndex``: int
        - ``accounts``: list[int]
        - ``data``: base58 str
    """
    if not tx_json.get("transaction"):
        return []

    message = tx_json["transaction"].get("message", {})
    account_keys = message.get("accountKeys", [])
    instructions = message.get("instructions", [])

    program_id_str = str(PROGRAM_ID)
    polymind_indices = {
        idx for idx, key in enumerate(account_keys) if key == program_id_str
    }

    result: list[tuple[int, dict[str, Any]]] = []
    for ix_index, ix in enumerate(instructions):
        if ix.get("programIdIndex") in polymind_indices:
            result.append((ix_index, ix))
    return result


def _decode_instruction_data(ix: dict[str, Any]) -> bytes:
    """Decode base58 instruction data to raw bytes."""
    try:
        import base58
    except ImportError as exc:
        raise ChainParserError("base58 package is required for instruction decoding") from exc

    data_b58 = ix.get("data", "")
    if not data_b58:
        return b""
    return base58.b58decode(data_b58)


def _match_instruction(discriminator: bytes) -> PolyMindInstruction | None:
    """Map an 8-byte discriminator to a known instruction."""
    for instr, disc in INSTRUCTION_DISCRIMINATORS.items():
        if disc == discriminator:
            return instr
    return None


def _match_event(discriminator: bytes) -> PolyMindEventType | None:
    """Map an 8-byte discriminator to a known event."""
    for evt, disc in EVENT_DISCRIMINATORS.items():
        if disc == discriminator:
            return evt
    return None


def _decode_event_payload(event_type: PolyMindEventType, raw_payload: bytes) -> Any:
    """Decode raw Borsh bytes into a typed payload dataclass.

    TODO: implement real Borsh decoding once the Anchor IDL is stable.
    Until then, return a dataclass with type-appropriate default values.
    """
    payload_cls = EVENT_PAYLOAD_TYPES.get(event_type)
    if payload_cls is None:
        return {"_raw": raw_payload.hex()}

    fields: dict[str, Any] = {}
    for name, f in payload_cls.__dataclass_fields__.items():
        ftype = f.type
        if ftype is int or ftype == "int":
            fields[name] = 0
        elif ftype is bool or ftype == "bool":
            fields[name] = False
        else:
            fields[name] = ""
    return payload_cls(**fields)  # type: ignore[call-arg]


def _parse_program_logs(logs: list[str] | None) -> list[PolyMindEvent]:
    """Scan Solana program logs for Anchor ``Program data:`` events."""
    import base64

    events: list[PolyMindEvent] = []
    if not logs:
        return events

    prefix = "Program data: "
    event_index = 0
    for log in logs or []:
        if not log.startswith(prefix):
            continue
        encoded = log[len(prefix) :].strip()
        try:
            data = base64.b64decode(encoded)
        except Exception:
            continue
        if len(data) < DISCRIMINATOR_LENGTH:
            continue
        discriminator = data[:DISCRIMINATOR_LENGTH]
        raw_payload = data[DISCRIMINATOR_LENGTH:]
        event_type = _match_event(discriminator)
        if event_type is None:
            continue
        payload = _decode_event_payload(event_type, raw_payload)
        events.append(PolyMindEvent(type=event_type, event_index=event_index, payload=payload))
        event_index += 1
    return events


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


async def fetch_and_parse_transaction(
    signature: str,
    client: SolanaClient | None = None,
) -> ParsedTransaction:
    """Fetch a transaction from Solana RPC and parse PolyMind instructions/events.

    Args:
        signature: the transaction signature to fetch.
        client: optional existing ``SolanaClient``. If omitted, a new client is
            created and closed automatically.

    Raises:
        ChainParserError: if the transaction is not found or failed.
    """
    own_client = client is None
    active_client = SolanaClient() if own_client else client
    try:
        tx_json = await active_client.get_transaction(signature)
    finally:
        if own_client:
            await active_client.close()

    if tx_json is None:
        raise ChainParserError(f"transaction not found: {signature}")

    meta = tx_json.get("meta", {})
    err = meta.get("err")
    if err is not None:
        raise ChainParserError(f"transaction failed: {err}")

    message = tx_json["transaction"]["message"]
    account_keys = message.get("accountKeys", [])
    if not account_keys:
        raise ChainParserError("transaction has no account keys")

    # The fee payer / primary signer is the first account in the message.
    signer = account_keys[0]
    slot = tx_json.get("slot", 0)
    block_time = tx_json.get("blockTime")

    polymind_instructions: list[ParsedInstruction] = []
    for _, ix in _get_program_instructions(tx_json):
        raw_data = _decode_instruction_data(ix)
        if len(raw_data) < DISCRIMINATOR_LENGTH:
            continue
        discriminator = raw_data[:DISCRIMINATOR_LENGTH]
        instr_name = _match_instruction(discriminator)
        if instr_name is None:
            continue
        accounts = [account_keys[i] for i in ix.get("accounts", []) if i < len(account_keys)]
        polymind_instructions.append(
            ParsedInstruction(
                instruction_name=instr_name,
                signer=signer,
                accounts=accounts,
                data={"_raw": raw_data[DISCRIMINATOR_LENGTH:].hex()},
            )
        )

    polymind_events = _parse_program_logs(meta.get("logMessages", []))

    return ParsedTransaction(
        signature=signature,
        slot=slot,
        block_time=block_time,
        success=True,
        signer=signer,
        polymind_instructions=polymind_instructions,
        polymind_events=polymind_events,
    )


def verify_instruction(
    parsed: ParsedTransaction,
    expected_instruction: PolyMindInstruction,
    expected_signer: str | None = None,
) -> ParsedInstruction:
    """Verify that a parsed transaction contains exactly one expected instruction."""
    matches = [
        ix for ix in parsed.polymind_instructions if ix.instruction_name == expected_instruction
    ]
    if not matches:
        raise ChainParserError(
            f"expected instruction {expected_instruction.value} not found in transaction"
        )
    if len(matches) > 1:
        raise ChainParserError(
            f"expected exactly one {expected_instruction.value} instruction, found {len(matches)}"
        )
    ix = matches[0]
    if expected_signer is not None and ix.signer != expected_signer:
        raise ChainParserError(f"expected signer {expected_signer}, got {ix.signer}")
    return ix


def verify_event(
    parsed: ParsedTransaction,
    expected_event_type: PolyMindEventType,
) -> PolyMindEvent:
    """Verify that a parsed transaction emits exactly one expected event."""
    matches = [ev for ev in parsed.polymind_events if ev.type == expected_event_type]
    if not matches:
        raise ChainParserError(f"expected event {expected_event_type.value} not found in logs")
    if len(matches) > 1:
        raise ChainParserError(
            f"expected exactly one {expected_event_type.value} event, found {len(matches)}"
        )
    return matches[0]


# ---------------------------------------------------------------------------
# Convenience wrappers for API endpoints
# ---------------------------------------------------------------------------


async def verify_creator_action(
    signature: str,
    expected_instruction: PolyMindInstruction,
    creator_address: str,
) -> ParsedInstruction:
    """Verify a creator-only action (propose/finalize/void)."""
    parsed = await fetch_and_parse_transaction(signature)
    return verify_instruction(parsed, expected_instruction, expected_signer=creator_address)


async def verify_admin_action(
    signature: str,
    expected_instruction: PolyMindInstruction,
    admin_address: str,
) -> ParsedInstruction:
    """Verify an admin action (admin_finalize/admin_resolve)."""
    parsed = await fetch_and_parse_transaction(signature)
    return verify_instruction(parsed, expected_instruction, expected_signer=admin_address)


async def verify_dispute_bond(
    signature: str,
    expected_disputer: str,
) -> PolyMindEvent:
    """Verify a dispute bond deposit transaction.

    Returns the ``BondDeposited`` event payload. The caller should further
    validate the event's ``event_id`` / ``market_idx`` / ``disputer`` fields
    once the Borsh schema is known.
    """
    parsed = await fetch_and_parse_transaction(signature)
    verify_instruction(parsed, PolyMindInstruction.FILE_DISPUTE, expected_signer=expected_disputer)
    return verify_event(parsed, PolyMindEventType.BOND_DEPOSITED)


async def verify_claim(
    signature: str,
    expected_claimer: str,
) -> ParsedInstruction:
    """Verify a claim transaction."""
    parsed = await fetch_and_parse_transaction(signature)
    return verify_instruction(parsed, PolyMindInstruction.CLAIM, expected_signer=expected_claimer)


async def verify_trade(
    signature: str,
) -> ParsedInstruction:
    """Verify a bet/swap transaction.

    The caller should compare the bettor address with the user who called sync.
    """
    parsed = await fetch_and_parse_transaction(signature)
    return verify_instruction(parsed, PolyMindInstruction.BET)
