"""add phase4 chat reward_payouts batch_transfers

Revision ID: 0231a683b18e
Revises: 790143c99274
Create Date: 2026-07-09 14:30:17.193856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0231a683b18e'
down_revision: Union[str, None] = '790143c99274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_address', sa.String(length=64), nullable=True),
    sa.Column('recipient_address', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('token_mint', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tx_signature', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_transfers_recipient_address'), 'batch_transfers', ['recipient_address'], unique=False)
    op.create_index(op.f('ix_batch_transfers_sender_address'), 'batch_transfers', ['sender_address'], unique=False)
    op.create_index(op.f('ix_batch_transfers_status'), 'batch_transfers', ['status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_address', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_address'), 'chat_messages', ['user_address'], unique=False)
    op.create_table('reward_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_address', sa.String(length=64), nullable=False),
    sa.Column('payout_type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tx_signature', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_payouts_payout_type'), 'reward_payouts', ['payout_type'], unique=False)
    op.create_index(op.f('ix_reward_payouts_status'), 'reward_payouts', ['status'], unique=False)
    op.create_index(op.f('ix_reward_payouts_user_address'), 'reward_payouts', ['user_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reward_payouts_user_address'), table_name='reward_payouts')
    op.drop_index(op.f('ix_reward_payouts_status'), table_name='reward_payouts')
    op.drop_index(op.f('ix_reward_payouts_payout_type'), table_name='reward_payouts')
    op.drop_table('reward_payouts')
    op.drop_index(op.f('ix_chat_messages_user_address'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_batch_transfers_status'), table_name='batch_transfers')
    op.drop_index(op.f('ix_batch_transfers_sender_address'), table_name='batch_transfers')
    op.drop_index(op.f('ix_batch_transfers_recipient_address'), table_name='batch_transfers')
    op.drop_table('batch_transfers')
    # ### end Alembic commands ###
