"""add chain_event_log table

Revision ID: 364027c39c45
Revises: f37dbb19e639
Create Date: 2026-07-08 14:42:28.901900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '364027c39c45'
down_revision: Union[str, None] = 'f37dbb19e639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain_event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.Column('slot', sa.BigInteger(), nullable=False),
    sa.Column('block_time', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chain_event_log_actor'), 'chain_event_log', ['actor'], unique=False)
    op.create_index(op.f('ix_chain_event_log_kind'), 'chain_event_log', ['kind'], unique=False)
    op.create_index(op.f('ix_chain_event_log_program_id'), 'chain_event_log', ['program_id'], unique=False)
    op.create_index('ix_chain_event_log_signature_kind', 'chain_event_log', ['signature', 'kind'], unique=True)
    op.create_index(op.f('ix_chain_event_log_slot'), 'chain_event_log', ['slot'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chain_event_log_slot'), table_name='chain_event_log')
    op.drop_index('ix_chain_event_log_signature_kind', table_name='chain_event_log')
    op.drop_index(op.f('ix_chain_event_log_program_id'), table_name='chain_event_log')
    op.drop_index(op.f('ix_chain_event_log_kind'), table_name='chain_event_log')
    op.drop_index(op.f('ix_chain_event_log_actor'), table_name='chain_event_log')
    op.drop_table('chain_event_log')
    # ### end Alembic commands ###
