"""add phase3 admin tables

Revision ID: 790143c99274
Revises: a72257d59122
Create Date: 2026-07-09 13:57:21.173585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '790143c99274'
down_revision: Union[str, None] = 'a72257d59122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('subtitle', sa.String(length=512), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('action_url', sa.String(length=1024), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('total_markets', sa.Integer(), nullable=False),
    sa.Column('new_markets', sa.Integer(), nullable=False),
    sa.Column('total_bet_amount', sa.BigInteger(), nullable=False),
    sa.Column('total_claim_amount', sa.BigInteger(), nullable=False),
    sa.Column('total_disputes', sa.Integer(), nullable=False),
    sa.Column('pending_disputes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_stats_stat_date'), 'dashboard_stats', ['stat_date'], unique=True)
    op.create_table('media_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('uploader_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_address', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('action_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_messages_recipient_address'), 'push_messages', ['recipient_address'], unique=False)
    op.create_index(op.f('ix_push_messages_status'), 'push_messages', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_messages_status'), table_name='push_messages')
    op.drop_index(op.f('ix_push_messages_recipient_address'), table_name='push_messages')
    op.drop_table('push_messages')
    op.drop_table('media_images')
    op.drop_index(op.f('ix_dashboard_stats_stat_date'), table_name='dashboard_stats')
    op.drop_table('dashboard_stats')
    op.drop_table('activities')
    # ### end Alembic commands ###
