"""add admin audit and finalization metadata

Revision ID: 7f2c07b2d699
Revises: 0231a683b18e
Create Date: 2026-07-09 16:01:36.353287

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7f2c07b2d699'
down_revision: str | None = '0231a683b18e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('finalization_path', sa.SmallInteger(), nullable=True))
    op.add_column('markets', sa.Column('admin_reason', sa.Text(), nullable=True))
    op.create_check_constraint(
        'ck_markets_finalization_path',
        'markets',
        sa.text('finalization_path IN (1, 2, 3)'),
    )

    op.add_column('disputes', sa.Column('resolved_reason', sa.Text(), nullable=True))

    op.create_table(
        'admin_audit_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('admin_address', sa.String(length=64), nullable=False),
        sa.Column('action', sa.String(length=48), nullable=False),
        sa.Column('market_id', sa.Integer(), nullable=True),
        sa.Column('dispute_id', sa.Integer(), nullable=True),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('tx_signature', sa.String(length=128), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_admin_audit_log_action'), 'admin_audit_log', ['action'], unique=False
    )
    op.create_index(
        op.f('ix_admin_audit_log_admin_address'),
        'admin_audit_log',
        ['admin_address'],
        unique=False,
    )
    op.create_index(
        op.f('ix_admin_audit_log_created_at'),
        'admin_audit_log',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_admin_audit_log_dispute_id'),
        'admin_audit_log',
        ['dispute_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_admin_audit_log_market_id'),
        'admin_audit_log',
        ['market_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_admin_audit_log_tx_signature'),
        'admin_audit_log',
        ['tx_signature'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_audit_log_tx_signature'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_market_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_dispute_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_created_at'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_admin_address'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_action'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    op.drop_column('disputes', 'resolved_reason')
    op.drop_constraint('ck_markets_finalization_path', table_name='markets')
    op.drop_column('markets', 'admin_reason')
    op.drop_column('markets', 'finalization_path')
    # ### end Alembic commands ###
