"""add event slug

Revision ID: a72257d59122
Revises: d70924df1758
Create Date: 2026-07-09 04:17:31.266735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a72257d59122'
down_revision: Union[str, None] = 'd70924df1758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('slug', sa.String(length=256), server_default='', nullable=False))
    op.alter_column('events', 'slug', server_default=None)
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_column('events', 'slug')
    # ### end Alembic commands ###
