"""phase2_mvp_tables

Revision ID: a7aaa0c86803
Revises: 364027c39c45
Create Date: 2026-07-08 22:19:59.246306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7aaa0c86803'
down_revision: Union[str, None] = '364027c39c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_accounts_address'), 'admin_accounts', ['address'], unique=True)
    op.create_table('configs',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('memo', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('event_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_categories_slug'), 'event_categories', ['slug'], unique=True)
    op.create_table('indexer_cursor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.BigInteger(), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inviter_address', sa.String(length=64), nullable=False),
    sa.Column('invitee_address', sa.String(length=64), nullable=False),
    sa.Column('invite_code_used', sa.String(length=32), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_invitee_address'), 'referrals', ['invitee_address'], unique=True)
    op.create_index(op.f('ix_referrals_inviter_address'), 'referrals', ['inviter_address'], unique=False)
    op.create_index(op.f('ix_referrals_status'), 'referrals', ['status'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onchain_event_id', sa.String(length=64), nullable=True),
    sa.Column('creator_address', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_trending', sa.Boolean(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('can_share', sa.Boolean(), nullable=False),
    sa.Column('can_bet', sa.Boolean(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_yes_pool', sa.BigInteger(), nullable=False),
    sa.Column('total_no_pool', sa.BigInteger(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('players_count', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_mint', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['event_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_category_id'), 'events', ['category_id'], unique=False)
    op.create_index(op.f('ix_events_creator_address'), 'events', ['creator_address'], unique=False)
    op.create_index(op.f('ix_events_deadline'), 'events', ['deadline'], unique=False)
    op.create_index(op.f('ix_events_onchain_event_id'), 'events', ['onchain_event_id'], unique=True)
    op.create_index(op.f('ix_events_source'), 'events', ['source'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_table('event_tags',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'tag_id')
    )
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('market_idx', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('onchain_market_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('label_yes', sa.String(length=128), nullable=False),
    sa.Column('label_no', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('min_bet', sa.BigInteger(), nullable=False),
    sa.Column('yes_pool', sa.BigInteger(), nullable=False),
    sa.Column('no_pool', sa.BigInteger(), nullable=False),
    sa.Column('bonus_pool', sa.BigInteger(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('players_count', sa.Integer(), nullable=False),
    sa.Column('proposed_outcome', sa.String(length=16), nullable=True),
    sa.Column('proposed_by', sa.String(length=64), nullable=True),
    sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_outcome', sa.String(length=16), nullable=True),
    sa.Column('finalized_by', sa.String(length=64), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispute_active', sa.Boolean(), nullable=False),
    sa.Column('creator_seed_bet_amount', sa.BigInteger(), nullable=False),
    sa.Column('creator_seed_bet_side', sa.String(length=16), nullable=True),
    sa.Column('creator_seed_bet_tx', sa.String(length=128), nullable=True),
    sa.Column('creator_propose_timeout', sa.BigInteger(), nullable=False),
    sa.Column('platform_fee_bps', sa.Integer(), nullable=False),
    sa.Column('platform_fee_max', sa.BigInteger(), nullable=False),
    sa.Column('creator_reward_bps', sa.Integer(), nullable=False),
    sa.Column('creator_reward_max', sa.BigInteger(), nullable=False),
    sa.Column('dispute_window_secs', sa.BigInteger(), nullable=False),
    sa.Column('admin_timeout_secs', sa.BigInteger(), nullable=False),
    sa.Column('vault_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'market_idx', name='uq_market_event_idx')
    )
    op.create_index(op.f('ix_markets_deadline'), 'markets', ['deadline'], unique=False)
    op.create_index(op.f('ix_markets_event_id'), 'markets', ['event_id'], unique=False)
    op.create_index(op.f('ix_markets_onchain_market_id'), 'markets', ['onchain_market_id'], unique=True)
    op.create_index(op.f('ix_markets_slug'), 'markets', ['slug'], unique=True)
    op.create_index(op.f('ix_markets_status'), 'markets', ['status'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('disputer_address', sa.String(length=64), nullable=False),
    sa.Column('claimed_outcome', sa.String(length=16), nullable=True),
    sa.Column('bond_amount', sa.BigInteger(), nullable=False),
    sa.Column('bond_tx_signature', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolved_outcome', sa.String(length=16), nullable=True),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_disputer_address'), 'disputes', ['disputer_address'], unique=False)
    op.create_index(op.f('ix_disputes_market_id'), 'disputes', ['market_id'], unique=False)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_address', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('action_url', sa.String(length=1024), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_notifications_market_id'), 'notifications', ['market_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_address'), 'notifications', ['user_address'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('user_address', sa.String(length=64), nullable=False),
    sa.Column('yes_amount', sa.BigInteger(), nullable=False),
    sa.Column('no_amount', sa.BigInteger(), nullable=False),
    sa.Column('claimed_amount', sa.BigInteger(), nullable=False),
    sa.Column('payout_amount', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'user_address', name='uq_position_market_user')
    )
    op.create_index(op.f('ix_positions_market_id'), 'positions', ['market_id'], unique=False)
    op.create_index(op.f('ix_positions_user_address'), 'positions', ['user_address'], unique=False)
    op.create_table('referral_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tx_signature', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_rewards_market_id'), 'referral_rewards', ['market_id'], unique=False)
    op.create_index(op.f('ix_referral_rewards_referral_id'), 'referral_rewards', ['referral_id'], unique=False)
    op.create_index(op.f('ix_referral_rewards_status'), 'referral_rewards', ['status'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('user_address', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('tx_signature', sa.String(length=128), nullable=False),
    sa.Column('slot', sa.BigInteger(), nullable=True),
    sa.Column('block_time', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_signature')
    )
    op.create_index(op.f('ix_trades_market_id'), 'trades', ['market_id'], unique=False)
    op.create_index(op.f('ix_trades_slot'), 'trades', ['slot'], unique=False)
    op.create_index(op.f('ix_trades_user_address'), 'trades', ['user_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_user_address'), table_name='trades')
    op.drop_index(op.f('ix_trades_slot'), table_name='trades')
    op.drop_index(op.f('ix_trades_market_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_referral_rewards_status'), table_name='referral_rewards')
    op.drop_index(op.f('ix_referral_rewards_referral_id'), table_name='referral_rewards')
    op.drop_index(op.f('ix_referral_rewards_market_id'), table_name='referral_rewards')
    op.drop_table('referral_rewards')
    op.drop_index(op.f('ix_positions_user_address'), table_name='positions')
    op.drop_index(op.f('ix_positions_market_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_notifications_user_address'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_market_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_market_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_disputer_address'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_markets_status'), table_name='markets')
    op.drop_index(op.f('ix_markets_slug'), table_name='markets')
    op.drop_index(op.f('ix_markets_onchain_market_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_event_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_deadline'), table_name='markets')
    op.drop_table('markets')
    op.drop_table('event_tags')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_source'), table_name='events')
    op.drop_index(op.f('ix_events_onchain_event_id'), table_name='events')
    op.drop_index(op.f('ix_events_deadline'), table_name='events')
    op.drop_index(op.f('ix_events_creator_address'), table_name='events')
    op.drop_index(op.f('ix_events_category_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_referrals_status'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_inviter_address'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_invitee_address'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_table('indexer_cursor')
    op.drop_index(op.f('ix_event_categories_slug'), table_name='event_categories')
    op.drop_table('event_categories')
    op.drop_table('configs')
    op.drop_index(op.f('ix_admin_accounts_address'), table_name='admin_accounts')
    op.drop_table('admin_accounts')
    # ### end Alembic commands ###
