"""add event_index to chain_event_log

Revision ID: c3787f5e5df3
Revises: 7f2c07b2d699
Create Date: 2026-07-09 18:59:58.864917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3787f5e5df3'
down_revision: Union[str, None] = '7f2c07b2d699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chain_event_log', sa.Column('event_index', sa.Integer(), nullable=False, server_default='0'))
    op.drop_index(op.f('ix_chain_event_log_signature_kind'), table_name='chain_event_log')
    op.create_index('ix_chain_event_log_signature_kind_idx', 'chain_event_log', ['signature', 'kind', 'event_index'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chain_event_log_signature_kind_idx', table_name='chain_event_log')
    op.create_index(op.f('ix_chain_event_log_signature_kind'), 'chain_event_log', ['signature', 'kind'], unique=True)
    op.drop_column('chain_event_log', 'event_index')
    # ### end Alembic commands ###
