"""add expired_propose_mode and single_side_only to markets

Revision ID: cf73ea66724a
Revises: c3787f5e5df3
Create Date: 2026-07-09 19:48:47.316660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf73ea66724a'
down_revision: Union[str, None] = 'c3787f5e5df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('expired_propose_mode', sa.SmallInteger(), nullable=False))
    op.add_column('markets', sa.Column('single_side_only', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markets', 'single_side_only')
    op.drop_column('markets', 'expired_propose_mode')
    # ### end Alembic commands ###
