"""add auth nonce creator rewards and admin resource tables

Revision ID: d70924df1758
Revises: a7aaa0c86803
Create Date: 2026-07-09 03:57:46.303658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd70924df1758'
down_revision: Union[str, None] = 'a7aaa0c86803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_nonces',
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('nonce')
    )
    op.create_index(op.f('ix_login_nonces_address'), 'login_nonces', ['address'], unique=False)
    op.create_table('creator_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('creator_address', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('claim_tx_signature', sa.String(length=128), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_rewards_creator_address'), 'creator_rewards', ['creator_address'], unique=False)
    op.create_index(op.f('ix_creator_rewards_market_id'), 'creator_rewards', ['market_id'], unique=False)
    op.create_index(op.f('ix_creator_rewards_status'), 'creator_rewards', ['status'], unique=False)
    op.add_column('admin_accounts', sa.Column('label', sa.String(length=128), nullable=True))
    op.add_column('admin_accounts', sa.Column('added_by', sa.String(length=64), nullable=True))
    op.add_column('configs', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('markets', sa.Column('creator_address', sa.String(length=64), server_default='', nullable=False))
    op.add_column('markets', sa.Column('creator_performed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('markets', sa.Column('platform_rake', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('markets', sa.Column('creator_reward', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('markets', sa.Column('distributable_pool', sa.BigInteger(), server_default='0', nullable=False))
    op.create_index(op.f('ix_markets_creator_address'), 'markets', ['creator_address'], unique=False)
    op.add_column('tags', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    op.add_column('tags', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('tags', sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'is_pinned')
    op.drop_column('tags', 'is_active')
    op.drop_column('tags', 'sort_order')
    op.drop_index(op.f('ix_markets_creator_address'), table_name='markets')
    op.drop_column('markets', 'distributable_pool')
    op.drop_column('markets', 'creator_reward')
    op.drop_column('markets', 'platform_rake')
    op.drop_column('markets', 'creator_performed')
    op.drop_column('markets', 'creator_address')
    op.drop_column('configs', 'is_public')
    op.drop_column('admin_accounts', 'added_by')
    op.drop_column('admin_accounts', 'label')
    op.drop_index(op.f('ix_creator_rewards_status'), table_name='creator_rewards')
    op.drop_index(op.f('ix_creator_rewards_market_id'), table_name='creator_rewards')
    op.drop_index(op.f('ix_creator_rewards_creator_address'), table_name='creator_rewards')
    op.drop_table('creator_rewards')
    op.drop_index(op.f('ix_login_nonces_address'), table_name='login_nonces')
    op.drop_table('login_nonces')
    # ### end Alembic commands ###
