"""add admin compatibility tables

Revision ID: df6463fb62f4
Revises: cf73ea66724a
Create Date: 2026-07-09 20:08:19.737772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6463fb62f4'
down_revision: Union[str, None] = 'cf73ea66724a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_event_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_event_admins_address'), 'admin_event_admins', ['address'], unique=True)
    op.create_table('campaign_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(length=128), nullable=False),
    sa.Column('lang', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('window_label', sa.String(length=256), nullable=True),
    sa.Column('pick_label', sa.String(length=256), nullable=True),
    sa.Column('option_labels', sa.Text(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_campaign_meta_campaign_id'), 'campaign_meta', ['campaign_id'], unique=False)
    op.create_table('claim_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('user_address', sa.String(length=64), nullable=True),
    sa.Column('amount_base', sa.String(length=64), nullable=False),
    sa.Column('reward_ids', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_requests_status'), 'claim_requests', ['status'], unique=False)
    op.create_index(op.f('ix_claim_requests_uid'), 'claim_requests', ['uid'], unique=False)
    op.create_table('invite_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inviter_luffa_id', sa.String(length=64), nullable=False),
    sa.Column('pending_base', sa.String(length=64), nullable=False),
    sa.Column('paid_base', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_balances_inviter_luffa_id'), 'invite_balances', ['inviter_luffa_id'], unique=True)
    op.create_table('invite_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inviter_luffa_id', sa.String(length=64), nullable=False),
    sa.Column('invitee_luffa_id', sa.String(length=64), nullable=False),
    sa.Column('invitee_address', sa.String(length=64), nullable=True),
    sa.Column('onchain_event_id', sa.BigInteger(), nullable=True),
    sa.Column('market_idx', sa.Integer(), nullable=True),
    sa.Column('bet_tx_version', sa.String(length=64), nullable=True),
    sa.Column('bet_tx_index', sa.Integer(), nullable=True),
    sa.Column('bet_amount_base', sa.String(length=64), nullable=False),
    sa.Column('reward_base', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_tx_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_rewards_invitee_address'), 'invite_rewards', ['invitee_address'], unique=False)
    op.create_index(op.f('ix_invite_rewards_invitee_luffa_id'), 'invite_rewards', ['invitee_luffa_id'], unique=False)
    op.create_index(op.f('ix_invite_rewards_inviter_luffa_id'), 'invite_rewards', ['inviter_luffa_id'], unique=False)
    op.create_index(op.f('ix_invite_rewards_status'), 'invite_rewards', ['status'], unique=False)
    op.add_column('chain_event_log', sa.Column('module', sa.String(length=64), nullable=True))
    op.add_column('chain_event_log', sa.Column('subject', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_chain_event_log_module'), 'chain_event_log', ['module'], unique=False)
    op.create_index('ix_chain_event_log_module_subject_kind', 'chain_event_log', ['module', 'subject', 'kind'], unique=False)
    op.create_index(op.f('ix_chain_event_log_subject'), 'chain_event_log', ['subject'], unique=False)
    op.add_column('users', sa.Column('inviter_bound_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'inviter_bound_at')
    op.drop_index(op.f('ix_chain_event_log_subject'), table_name='chain_event_log')
    op.drop_index('ix_chain_event_log_module_subject_kind', table_name='chain_event_log')
    op.drop_index(op.f('ix_chain_event_log_module'), table_name='chain_event_log')
    op.drop_column('chain_event_log', 'subject')
    op.drop_column('chain_event_log', 'module')
    op.drop_index(op.f('ix_invite_rewards_status'), table_name='invite_rewards')
    op.drop_index(op.f('ix_invite_rewards_inviter_luffa_id'), table_name='invite_rewards')
    op.drop_index(op.f('ix_invite_rewards_invitee_luffa_id'), table_name='invite_rewards')
    op.drop_index(op.f('ix_invite_rewards_invitee_address'), table_name='invite_rewards')
    op.drop_table('invite_rewards')
    op.drop_index(op.f('ix_invite_balances_inviter_luffa_id'), table_name='invite_balances')
    op.drop_table('invite_balances')
    op.drop_index(op.f('ix_claim_requests_uid'), table_name='claim_requests')
    op.drop_index(op.f('ix_claim_requests_status'), table_name='claim_requests')
    op.drop_table('claim_requests')
    op.drop_index(op.f('ix_campaign_meta_campaign_id'), table_name='campaign_meta')
    op.drop_table('campaign_meta')
    op.drop_index(op.f('ix_admin_event_admins_address'), table_name='admin_event_admins')
    op.drop_table('admin_event_admins')
    # ### end Alembic commands ###
