[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
polymind = "GRzZ7B6ZzgU2TuvmTFhtPHbc98CScGLw6h5McTM4SXT5"

[programs.localnet]
polymind = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
