skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
polymind = "7c7Btev54kA36Nx5iq6LrzBhT9K4p6hKD1Tv4CjZ7qAv"

[programs.localnet]
polymind = "7c7Btev54kA36Nx5iq6LrzBhT9K4p6hKD1Tv4CjZ7qAv"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
